spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
logging:
  level:
    root: INFO
    com.company.runcoach: DEBUG

runcoach:
  integrations:
    strava:
      client-id: local-client
      client-secret: local-dev-strava-client-secret
      token-encryption-secret: local-dev-token-encryption-secret
  security:
    jwt:
      secret: local-dev-jwt-secret-local-dev-jwt-secret
